CREATE TABLE IF NOT EXISTS USERS (
  id MEDIUMINT NOT NULL AUTO_INCREMENT,
  username   VARCHAR(60)  NOT NULL,
  password   VARCHAR(60)      NOT NULL,
  deposit    DECIMAL     NOT NULL,
  role    CHAR(20)   NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PRODUCTS (
  id MEDIUMINT NOT NULL AUTO_INCREMENT,
  productname   VARCHAR(60)  NOT NULL,
  quantityavailable    DECIMAL     NOT NULL,
  cost    DECIMAL     NOT NULL,
  sellerid INT NOT NULL,
  PRIMARY KEY (id)
);
